#!/usr/bin/env python3
"""Generate docs/DETECTIONS.md from the rules and their fixtures.

The catalogue is generated rather than written by hand so that it cannot describe a rule that
no longer exists or omit one that does.
"""

from __future__ import annotations

from pathlib import Path

from sigmatch.attack import render_markdown
from sigmatch.corpus import load_events
from sigmatch.correlation import load_correlations
from sigmatch.elastic import to_query
from sigmatch.rule import load_rules

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "DETECTIONS.md"

SOURCE_LABEL = {
    ("windows", "process_creation"): "Sysmon Event ID 1 (process creation), or Security 4688",
    ("windows", "process_access"): "Sysmon Event ID 10 (process access)",
    ("windows", "registry_set"): "Sysmon Event ID 12/13 (registry value set)",
    ("linux", "process_creation"): "Sysmon for Linux Event ID 1, or auditd execve",
}


def telemetry_source(rule) -> str:
    logsource = rule.logsource
    key = (logsource.get("product"), logsource.get("category"))
    if key in SOURCE_LABEL:
        return SOURCE_LABEL[key]
    if logsource.get("service") == "security":
        return "Windows Security channel"
    if logsource.get("service") == "system":
        return "Windows System channel"
    return ", ".join(f"{k}={v}" for k, v in logsource.items())


def main() -> None:
    rules = load_rules(ROOT / "detections")
    correlations = load_correlations(ROOT / "detections")
    benign = load_events(ROOT / "telemetry" / "benign" / "workstation_and_server_baseline.jsonl")

    lines = [
        "# Detection catalogue",
        "",
        "Generated by `scripts/generate_docs.py`. Edit the rules, not this file.",
        "",
        "## ATT&CK coverage",
        "",
        render_markdown(rules, correlations),
        "",
        "## Detections",
        "",
    ]

    for rule in sorted(rules, key=lambda r: r.path.stem):
        fixture = ROOT / "telemetry" / "true_positive" / f"{rule.path.stem}.jsonl"
        positives = load_events(fixture) if fixture.exists() else []
        query, language = to_query(rule)

        lines += [
            f"### {rule.title}",
            "",
            f"`{rule.path.relative_to(ROOT)}` &middot; **{rule.level}** &middot; "
            f"ATT&CK {', '.join(rule.attack_techniques) or 'n/a'}",
            "",
            " ".join(rule.description.split()),
            "",
            f"**Telemetry source.** {telemetry_source(rule)}",
            "",
            f"**Elastic query ({language}).**",
            "",
            "```",
            query,
            "```",
            "",
            f"**Investigation fields.** {', '.join(rule.fields)}",
            "",
        ]

        if rule.raw.get("investigation"):
            lines.append("**Investigation path.**")
            lines.append("")
            lines += [f"{n}. {step}" for n, step in enumerate(rule.raw["investigation"], 1)]
            lines.append("")

        lines.append("**Known false positives.**")
        lines.append("")
        lines += [f"- {fp}" for fp in rule.falsepositives]
        lines.append("")
        lines += [
            f"**Validation.** {len(positives)} true-positive fixture(s) in "
            f"`{fixture.relative_to(ROOT)}` must match; all {len(benign)} events in the benign "
            "baseline must not. Enforced by `tests/test_detections.py`.",
            "",
        ]

    for correlation in correlations:
        spec = correlation.spec
        operator, threshold = correlation.threshold
        lines += [
            f"### {correlation.title}",
            "",
            f"`{correlation.path.relative_to(ROOT)}` &middot; **{correlation.level}** &middot; "
            f"correlation ({correlation.type})",
            "",
            " ".join(correlation.raw.get("description", "").split()),
            "",
            f"**Aggregation.** {correlation.type} "
            f"{operator} {threshold} within {spec['timespan']}, grouped by "
            f"{', '.join(correlation.group_by)}"
            + (f", counting distinct {correlation.count_field}" if correlation.count_field else ""),
            "",
            "**Known false positives.**",
            "",
        ]
        lines += [f"- {fp}" for fp in correlation.raw.get("falsepositives", [])]
        lines += [
            "",
            "**Validation.** Fires on "
            "`telemetry/true_positive/authentication_bursts.jsonl` and stays silent on the "
            "benign baseline, including the isolated failed logons it contains. Sub-threshold "
            "and time-spread variants are asserted not to fire.",
            "",
        ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(rules)} rules, {len(correlations)} correlations)")


if __name__ == "__main__":
    main()
